// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'zz.models.models.testModel' );
goog.provide( 'zz.models.models.testModelDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
zz.models.models.testModelDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.test = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( zz.models.models.testModelDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
zz.models.models.testModel = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( zz.models.models.testModel, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {zz.models.models.testModelDatarow}
*/
zz.models.models.testModel.prototype.DatarowConstructor = zz.models.models.testModelDatarow;

/**
* Return zz.models.models.testModelDatarow schema object.
* @override
* @returns {Object}
*/
zz.models.models.testModel.prototype.getDatarowSchema = function( ){

return {
        test: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};